[package]
org = "ballerinai"
name = "runtime.management"
version = "@toml.version@"
distribution = "2201.9.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "../native/build/libs/runtime.management-native-@project.version@.jar"
